services:
  - type: web
    name: eaglercraft-wss-proxy
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: TARGET_HOST
        value: Davi_Gabriel__.aternos.me
      - key: TARGET_PORT
        value: "15630"
